### ISSUE TITLE
MBS dependency

### ISSUE THREAD

**Issue by mrwatson-de** [fmgarage/ft-buildinfo#2]
Great idea - let's just remove the dependency on the MBS plugin ;-)

**Comment by nilswald** [comment]
and done.

**Comment by nilswald** [comment]
It turned out, that the next serial value is not transferred in a migration – which makes total sense, as the current auto increment is in the domain of the source/production file and should not be changed. Nevertheless, we are able to push way more than 255k into the default value – check out the new version.
